export enum IWorkOrderActionType {
  WORK_ORDER_REQUEST = 'WORK_ORDER_REQUEST',
  WORK_ORDER_SUCCESS = 'WORK_ORDER_SUCCESS',
  WORK_ORDER_ERROR = 'WORK_ORDER_ERROR',
  WORK_ORDER_RESET = 'WORK_ORDER_RESET',
}
